name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          packer build ubuntu-2204.json
          ls output-vagrant
